name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Github Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
  Test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app && /usr/bin/xcodebuild -version
      - name: List all available simulators
        run: sudo xcrun simctl list
      - name: Run unit tests
        run: xcodebuild test -scheme Revisadinho -project Revisadinho.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' | xcpretty && exit ${PIPESTATUS[0]}    
